title: 极寒之域
author: HoshinoTented
keywords: HoshinoTented, blog, cirno
twitter: LimbolRain
email: limbolrain@gmail.com
description: >
  Hoshi no Blog
baseurl: ""
url: "http://www.tented.top"
github_username: HoshinoTented
markdown: kramdown
domain: tented.top
repository: https://github.com/HoshinoTented/hoshinotented.github.io
repository_name: hoshinotented.github.io